title=Spring Handbook
date=2020-03-01
type=post
tags=spring,springboot,webflux,graphql
status=published
~~~~~~

It's been a while since I've posted. There's been a lot going on (I've been very busy).
I started a new position at a large corporation here near Orlando (a mouse-themed amusement park; more on this later).

Meanwhile, I've finally started work on "Spring Handbook".

== Spring Handbook

I've been using Spring for a long, long time (since 2005).
It's been there throughout almost my entire Java development career and it's evolved substantially over the years.
I've had "Spring Handbook" on my check-list of books to write for a long time.

https://www.apress.com/us/book/9781484261439[Spring Quick Reference Guide]

It's going to be picked up by Apress, and is currently under development.
(\**Edit\** It's published!)
I'm really excited about this one - there is so much to cover and it's so relevant to software development today especially with Java.
I'm going to cover so many things:

- Core Spring
- Spring Data
- Spring Security
- Spring Boot
- Webflux and Reactor
- and tons more...

== GraphQL

In other news, I've learned a lot about https://graphql.org/[GraphQL] at my new job.

It's combines a typed schema with the ability for clients to tell the server exactly what they want.
This reduces the amount of unnecessary data requested, the number of HTTP requests needed, thereby increasing performance overall of a software system.
Although I was suspect at first, it's actually very clever. I've learned a lot about it and hope that I can share more about it later on.

